PYGAME_WINDOW_WIDTH = 1280
PYGAME_WINDOW_DEPTH = 768

BOARD_FILE = "images/monopoly_768*768.png"
BOARD_CENTERED_X = (PYGAME_WINDOW_WIDTH - PYGAME_WINDOW_DEPTH) / 2

tileWidth = 20
tileHeight = 40
FPS = 40

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
LIGHT_GREEN = (124, 252, 0)
GREEN = (0, 128, 0)
RED = (255, 0 , 0)
LIGHT_BLUE = (30, 144, 255)
BLUE = (0, 0, 255)
PURPLE = (153, 51, 255)
ORANGE = (255, 153, 51)
YELLOW = (255, 255, 0)

COLOR_SELECT = [
    RED,
    GREEN,
    BLUE,
    PURPLE,
    ORANGE,
    YELLOW
]

backgroundGreen = (224,246,234)
deepGreen = (0,204,0)
deepBlue = (0,128,255)
brown = (102,51,0)
slightBlue = (204,255,255)

TILE_LIMIT = 40

MENU_NONE = "NONE"
MENU_WAIT = "WAIT"
MENU_MAIN = "MAIN"
MENU_DICE = "DICE"
MENU_RESULT = "RESULT"
MENU_START = "START"
MENU_COLOR = "COLOR"
MENU_NAME = "NAME"
MENU_OPP_SEL = "OPPONENT"
MENU_BUY = "BUY"
MENU_RENT = "RENT"
MENU_OVER = "OVER"
MENU_AI_ROLL = "AI_ROLL"
MENU_AI_BUY = "AI_BUY"
MENU_END = "END"
MENU_AI_RENT = "AI_RENT"

PLAYER_GRAPHIC_RADIUS = 15
HUMAN_MARKER_RADIUS = 5
PLAYER_GRAPHIC_DIAMETER = 2 * PLAYER_GRAPHIC_RADIUS

OWNER_MARKER_RADIUS = 8
OWNER_MARKER_POSITION = (-10, -12)
HOUSE_MARKER_DIMENSIONS = (17, 17)
HOUSE_MARKER_TEXT_OFFSET = (5, 4)
HOUSE_MARKER_POSITION = (5, -HOUSE_MARKER_DIMENSIONS[1] - 5)
HOUSE_MARKER_TEXT_SIZE = 12


PlAYER_TILE_OFFSET = 20

EVENT_COUNT = 4

GUI_WINDOW_DIMENSIONS = (400, 500)
GUI_WINDOW_POSITION = (PYGAME_WINDOW_WIDTH / 2 - GUI_WINDOW_DIMENSIONS[0] / 2, PYGAME_WINDOW_DEPTH / 2 - GUI_WINDOW_DIMENSIONS[1] / 2)
GUI_WINDOW_COLOR = (205, 255, 220)
GUI_BORDER_WIDTH = 10

MENU_LABEL_SIZE = 40

BUTTON_DIMENSIONS = (150, 40)
BUTTON_COLOR = (220, 220, 220)
BUTTON_HIGHLIGHT = (150, 150, 150)
BUTTON_TEXT_COLOR = (0, 0, 0)
BUTTON_TEXT_SIZE = 20

TEXT_BOX_DIMENSIONS = (300, 60)
TEXT_BOX_COLOR = (140, 140, 140)
TEXT_BOX_HIGHLIGHT = (200, 200, 200)
TEXT_BOX_ACTIVE = (255, 255, 255)
TEXT_BOX_TEXT_COLOR = (0, 0, 0)
TEXT_BOX_TEXT_SIZE = 20

DICE_GRAPHIC_DIMENSIONS = (70, 70)
DICE_OFFSET = 75
DICE_GRAPHIC_COLOR = (255, 255, 255)
DICE_TEXT_COLOR = (0, 0, 0)
DICE_TEXT_SIZE = 50

TILE_LONG_AXIS = 103.
TILE_SHORT_AXIS = 62.25

TILE_BOUNDS = [((PYGAME_WINDOW_WIDTH - BOARD_CENTERED_X - TILE_LONG_AXIS, PYGAME_WINDOW_DEPTH - TILE_LONG_AXIS),
                (PYGAME_WINDOW_WIDTH - BOARD_CENTERED_X, float(PYGAME_WINDOW_DEPTH)))]
for i in range(9):
    TILE_BOUNDS.append(((PYGAME_WINDOW_WIDTH - BOARD_CENTERED_X - TILE_LONG_AXIS - TILE_SHORT_AXIS - i * TILE_SHORT_AXIS, PYGAME_WINDOW_DEPTH - TILE_LONG_AXIS),
                        (PYGAME_WINDOW_WIDTH - BOARD_CENTERED_X - TILE_LONG_AXIS - i * TILE_SHORT_AXIS, PYGAME_WINDOW_DEPTH)))

TILE_BOUNDS.append(((BOARD_CENTERED_X, PYGAME_WINDOW_DEPTH - TILE_LONG_AXIS),
                    (BOARD_CENTERED_X + TILE_LONG_AXIS, PYGAME_WINDOW_DEPTH)))
for i in range(9):
    TILE_BOUNDS.append(((BOARD_CENTERED_X, PYGAME_WINDOW_DEPTH - TILE_LONG_AXIS - TILE_SHORT_AXIS - i * TILE_SHORT_AXIS),
                        (BOARD_CENTERED_X + TILE_LONG_AXIS, PYGAME_WINDOW_DEPTH - TILE_LONG_AXIS - i * TILE_SHORT_AXIS)))

TILE_BOUNDS.append(((BOARD_CENTERED_X, 0.),
                    (BOARD_CENTERED_X + TILE_LONG_AXIS, TILE_LONG_AXIS)))
for i in range(9):
    TILE_BOUNDS.append(((BOARD_CENTERED_X + TILE_LONG_AXIS + i * TILE_SHORT_AXIS, 0.),
                        (BOARD_CENTERED_X + TILE_LONG_AXIS + TILE_SHORT_AXIS + i * TILE_SHORT_AXIS, TILE_LONG_AXIS)))

TILE_BOUNDS.append(((PYGAME_WINDOW_WIDTH - BOARD_CENTERED_X - TILE_LONG_AXIS, 0.),
                    (PYGAME_WINDOW_WIDTH - BOARD_CENTERED_X, TILE_LONG_AXIS)))
for i in range(9):
    TILE_BOUNDS.append(((PYGAME_WINDOW_WIDTH - BOARD_CENTERED_X - TILE_LONG_AXIS, TILE_LONG_AXIS + i * TILE_SHORT_AXIS),
                        (PYGAME_WINDOW_WIDTH - BOARD_CENTERED_X, TILE_LONG_AXIS + TILE_SHORT_AXIS + i * TILE_SHORT_AXIS)))

